### ISSUE TITLE
Using `with-access` in virtual-field getter does not work

### ISSUE THREAD

**Issue by FrankRuben** [manuel-serrano/hop#45] opened 2018-06-02 09:37 UTC
Hi,

I'm using "Hop-3.1.0", compiled with "Bigloo (4.3b)" and I'm trying to get something run with Hop (old-style: hop and scheme, no JS).

For that reason I also wrote a class with a virtual-field getter and got an error. I then checked the Hop sources and samples and found a similar code snippet (https://github.com/manuel-serrano/hop/blob/3.1.x/widget/audio.scm) and tried to compile that - compiling works fine in Bigloo, but fails with a similar error message as for my original source in Hop.

```scheme
(module test_getter_with_access
  (export  (class xaudio-server
                  (music (get (lambda (o) (with-access::xaudio-server o (%music) %music)))
                         read-only)
                  (%music (default #f)))))
```

The error when trying to run that using `hop test.hop` is:

```
File "test.hop", line 3, character 110:
#                  (music (get (lambda (o) (with-access::xaudio-server o (%music) %music)))
#                                          ^
*** ERROR:with-access::xaudio-server
Unknown class -- (with-access::xaudio-server o (%music) %music)
```

Using the same source in a file test.scm, no error when compiling with `bigloo test.scm`.

Any idea or pointer what to do?

Thanks in advance, Frank

**Comment by manuel-serrano** [comment] 2018-06-04 11:49
Hi Frank,

Thanks for the report. The error is actually in the Bigloo interpreter.
The problem is now fixed. A new Bigloo version has been pushed on github.
Checkout the NAN branch.

Best,

--
Manuel

**Comment by FrankRuben** [comment] 2018-10-07 19:12
Hi Manuel,

quite a late update, but I finally managed to compile a new Hop from current Github master with Bigloo 4.3c compiled from the source tarball and the issue is gone, meaning the source above now compiles just fine.

So thanks and best regards, Frank

**Closed** 2018-10-12 15:28 UTC
