### ISSUE TITLE
Auth required?

### ISSUE THREAD

**Issue by amirouche** [manuel-serrano/hop#59] opened 2019-02-26 13:07 UTC
When I go the website at http://hop.inria.fr/home/index.html and click on a click for instance `download` and I hit back, the browser request a login/password.

**Comment by svenha** [comment] 2019-02-26 14:00
Interesting. I can reproduce this behavior with Firefox 65, but not with Brave 0.57.18.

**Comment by manuel-serrano** [comment] 2019-02-26 18:44
Sorry for that problem. This should be fixed by now. 

Please note that if you are interested in programming Hop in JavaScript, then I strongly recommend using the branch 3.2.x as this version supports most ECMAScript 2016 features and because the compiler is much more efficient. On the other hand, if you are interested in Scheme only, 3.1.0 or 3.2.0 should not make a big difference.

**Comment by manuel-serrano** [comment] 2019-02-26 18:46
... but one more thing I have forgotten to mentioned. I have fixed a compiler bug in Bigloo today. Without that new version, you will be unable to compile Hop as Bigloo will loop forever while applying the inlining optimization stage.

**Comment by amirouche** [comment] 2019-02-26 22:58
I will first read the papers about hop, too bad the scheme documentation is gone?!

**Comment by svenha** [comment] 2019-02-27 06:35
http://hop.inria.fr/hop/doc is still there.

**Closed** 2021-12-06 09:57 UTC
